// theme.ts -> Contains theme config for React native paper.
import {
  MD3CustomTheme,
  MD3DarkTheme,
  MD3LightTheme,
  MD3ThemeFonts,
} from 'react-native-paper';
import {ms} from 'react-native-size-matters';

// Extend the MD3Typescale with custom fonts
const customFonts: MD3ThemeFonts = {
  displayLarge: {
    fontFamily: 'Roboto-Bold',
    fontWeight: '700',
    fontSize: ms(24),
    letterSpacing: 0,
    lineHeight: ms(30),
  },
  displayMedium: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(20),
    letterSpacing: 0,
    lineHeight: ms(24),
  },
  displaySmall: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(16),
    letterSpacing: 0,
    lineHeight: ms(18),
  },
  headlineLarge: {
    fontFamily: 'Roboto-Bold',
    fontWeight: '700',
    fontSize: ms(30),
    letterSpacing: 0,
    lineHeight: ms(36),
  },
  headlineMedium: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(18),
    letterSpacing: 0,
    lineHeight: ms(20),
  },
  headlineSmall: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(16),
    letterSpacing: 0,
    lineHeight: ms(18),
  },
  titleLarge: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(22),
    letterSpacing: 0,
    lineHeight: ms(24),
  },
  titleMedium: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(18),
    letterSpacing: 0,
    lineHeight: ms(20),
  },
  titleSmall: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '400',
    fontSize: ms(16),
    letterSpacing: 0,
    lineHeight: ms(14),
  },
  bodyLarge: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(16),
    letterSpacing: 0.1,
    lineHeight: ms(18),
  },
  bodyMedium: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(14),
    letterSpacing: 0.1,
    lineHeight: ms(16),
  },
  bodySmall: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '300',
    fontSize: ms(12),
    letterSpacing: 0.1,
    lineHeight: ms(14),
  },
  labelLarge: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(16),
    letterSpacing: 0.1,
    lineHeight: ms(18),
  },
  labelMedium: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(14),
    letterSpacing: 0.1,
    lineHeight: ms(16),
  },
  labelSmall: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(12),
    letterSpacing: 0.1,
    lineHeight: ms(14),
  },
  semiBold: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: ms(16),
    letterSpacing: 0.1,
    lineHeight: ms(18),
  },
  bold: {
    fontFamily: 'Roboto-Bold',
    fontWeight: '500',
    fontSize: ms(14),
    letterSpacing: 0.1,
    lineHeight: ms(16),
  },
  regular: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: ms(14),
    letterSpacing: 0.1,
    lineHeight: ms(16),
  },
  default: {
    fontWeight: '400',
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0.1,
  },
};

// Light Theme
export const lightTheme: MD3CustomTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#427BAB',
    onPrimary: '#FFFFFF',
    primaryContainer: '#D1E4FF',
    onPrimaryContainer: '#001D36',
    secondary: '#54677A',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D7E3F1',
    onSecondaryContainer: '#121C2A',
    tertiary: '#6B5F8C',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#E9DDFF',
    onTertiaryContainer: '#231737',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#FCFCFF',
    onBackground: '#1A1C1E',
    surface: '#FCFCFF',
    onSurface: '#1A1C1E',
    surfaceVariant: '#DEE3EB',
    onSurfaceVariant: '#42474E',
    outline: '#72777F',
    outlineVariant: '#C2C7CF',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2F3033',
    inverseOnSurface: '#F0F0F4',
    inversePrimary: '#A1C9FF',

    // Required custom colors
    success: '#4caf50', // Green
    warning: '#ff9800', // Orange
    info: '#2196f3', // Blue
    accent: '#ff4081', // Pink
    buttonColor: {
      regular: '#427BAB',
      alert: '#550000',
      error: '#AA2222',
      success: '#4caf50',
      reset: '#AE3232',
      submit: '#427BAB',
      cancel: '#D1E4FF',
      disabled: '#A5A5A5',
    },
    textColor: {
      regular: '#000000',
      alert: '#550000',
      error: '#AA2222',
      success: '#4caf50',
      placeholder: '#A5A5A5',
      white: '#FFFFFF',
      black: '#000000',
      primary: '#427BAB',
    },
    iconColor: {
      regular: '#000000',
      alert: '#550000',
      error: '#AA2222',
      success: '#4caf50',
      black: '#000000',
      white: '#FFFFFF',
    },
    statusBar: {
      backgroundColor: '#FFFFFF',
      iconColor: '#000000',
    },
    borderColor: {
      regular: '#427BAB',
      error: '#AA2222',
      success: '#44EE00',
      transparent: '#00000000',
      disabled: '#A5A5A5',
    },
    loader: {
      background: '#E9E9E999',
      backdrop: '#00000080',
      indicator: '#427BAB',
      shimmerBone: '#4D4D4D',
      shimmerHighlight: '#8E8E8E99',
    },
    dataTable: {
      headerBackground: '#E9E9E9',
      rowBackground: '#F5F5F5',
    },
    successContainer: '#E8F5E9',
    warningContainer: '#FFF3E0',
    infoContainer: '#E3F2FD',
  },
  fonts: customFonts,
  roundness: 8,
  radius: {
    buttonBorderRadius: {
      small: ms(8),
      regular: ms(12),
      large: ms(16),
      extraLarge: ms(20),
      circle: 999,
    },
  },
};

// Dark Theme
export const darkTheme: MD3CustomTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#A1C9FF',
    onPrimary: '#00325A',
    primaryContainer: '#214A7B',
    onPrimaryContainer: '#D1E4FF',
    secondary: '#BCC7D7',
    onSecondary: '#26333F',
    secondaryContainer: '#3D4A57',
    onSecondaryContainer: '#D7E3F1',
    tertiary: '#CDC0E9',
    onTertiary: '#392C4F',
    tertiaryContainer: '#504466',
    onTertiaryContainer: '#E9DDFF',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#1A1C1E',
    onBackground: '#E2E2E5',
    surface: '#1A1C1E',
    onSurface: '#E2E2E5',
    surfaceVariant: '#42474E',
    onSurfaceVariant: '#C2C7CF',
    outline: '#8C9198',
    outlineVariant: '#42474E',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#E2E2E5',
    inverseOnSurface: '#2F3033',
    inversePrimary: '#427BAB',

    // Required custom colors
    success: '#66bb6a', // Light Green
    warning: '#ffa726', // Light Orange
    info: '#29b6f6', // Light Blue
    accent: '#ff80ab', // Light Pink
    buttonColor: {
      regular: '#96CCFF',
      alert: '#550000',
      error: '#AA2222',
      success: '#44EE00',
      reset: '#AE3232',
      submit: '#96CCFF',
      cancel: '#030303',
      disabled: '#A5A5A5',
    },
    textColor: {
      regular: '#FFFFFF',
      alert: '#550000',
      error: '#AA2222',
      success: '#44EE00',
      placeholder: '#A5A5A5',
      white: '#FFFFFF',
      black: '#000000',
      primary: '#96CCFF',
    },
    iconColor: {
      regular: '#FFFFFF',
      alert: '#550000',
      error: '#AA2222',
      success: '#44EE00',
      black: '#000000',
      white: '#FFFFFF',
    },
    statusBar: {
      backgroundColor: '#000000',
      iconColor: '#FFFFFF',
    },
    borderColor: {
      regular: '#96CCFF',
      error: '#AA2222',
      success: '#44EE00',
      transparent: '#00000000',
      disabled: '#A5A5A5',
    },
    loader: {
      background: '#E9E9E999',
      backdrop: '#00000080',
      indicator: '#96CCFF',
      shimmerBone: '#1D1D1D',
      shimmerHighlight: '#E9E9E999',
    },
    dataTable: {
      headerBackground: '#494949',
      rowBackground: '#F5F5F5',
    },
    successContainer: '#114E20',
    warningContainer: '#DDA726',
    infoContainer: '#0D47A1',
  },
  fonts: customFonts,
  roundness: 8,
  radius: {
    buttonBorderRadius: {
      small: ms(8),
      regular: ms(12),
      large: ms(16),
      extraLarge: ms(20),
      circle: 999,
    },
  },
};
